"""G-UNPROMPTED-SYNTHETIC — a driven turn's CONTINUATION is driven too.

FOUND BY DOING IT, NOT BY READING IT (2026-09-02). Driving a real continuation on the live
stack to confirm that night's margin fix, the probe declared itself `synthetic` and the day
transcript came back:

    row 159  user       synthetic='live probe ...'   "What is the capital of France?"
    row 160  assistant  synthetic='live probe ...'   "Paris."
    row 161  user       synthetic='live probe ...'   "Describe a thunderstorm ..."
    row 162  assistant  synthetic='live probe ...'   "The horizon did not merely darken..."
    row 163  assistant  synthetic=None               "it was something you could chew..."

Row 163 is the continuation. The scheduler had also filed it as a real `spoke_up` memory
(`ep_tool_1788302245156`, quarantined after the fact — the fourth such cleanup).

THE SHAPE IS §0. `_finish_openai_turn` passes `synthetic=`; the native path passes it;
`_on_her_own_words` — the epilogue for EVERY unprompted turn — passed nothing at all. An
invariant enforced on two of three paths is enforced on none, because the unguarded path is
the one that runs.

Why it was invisible: the flag is carried by a ContextVar armed per REQUEST, and the
continuation is generated by the SCHEDULER's own thread minutes later, with no request body
in reach. So `on_reply` records the reason per session and `_arm` puts it back on the
ContextVar for the length of the unprompted turn.

SCOPE IS THE SESSION, NOT THE LANE — and the first cut of this gate had that wrong. It
scoped inheritance to CONTINUE and EXPAND, reasoning that only those two ARE the previous
turn. An hour later the live stack settled it: the idle ticker fired a CHECK_IN on the
probe's own session 657 s after it ended, regenerated the probe's text and filed it as a real
`spoke_up` (`ep_tool_1788302812000`, also quarantined). The ticker speaks from
`_LAST[session]` for as long as the session lives, so a lane-shaped rule leaves the hole open
on every lane it does not name.

What keeps her real speech safe is not the lane but the CLEARING: `on_reply` drops the
session's reason the moment a real turn arrives, so a probe cannot mute anything he is part
of. §1 pins that, and §2 pins that every lane inherits.

Lane: OFFLINE (the real scheduler, the real epilogue, a fake generate; no daemon, no GPU).
"""
import os
import sys
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from harness_tests._gate import sandbox, check, finish  # noqa: E402

sandbox()  # FIRST, before any harness. import

from harness.kairos import impulse as I  # noqa: E402
from harness.kairos import scheduler as KS  # noqa: E402
from harness.server import turn as T  # noqa: E402
from harness.skills import memory as M  # noqa: E402

REASON = "live gate g_unprompted_synthetic — driven, not their conversation"

print("0. THE THREE EPILOGUE PATHS AGREE THAT A DRIVEN TURN IS MARKED")
# Behavioural, not textual: call each and record what `_settle_turn` was handed. Patch the
# MODULE attribute — `_on_her_own_words` resolves `_settle_turn` through the module global,
# and a by-name import here would snapshot the real one and measure nothing.
seen = []
_real_settle = T._settle_turn
T._settle_turn = lambda human, reply, **kw: (seen.append((reply[:24], kw.get("synthetic"))), [])[1]
try:
    tok = M.set_synthetic(REASON)
    try:
        T._on_her_own_words("a continuation on a driven turn", None)
        T._on_her_own_words("a mode turn on a driven turn", "mode_turn")
    finally:
        M.reset_synthetic(tok)
    T._on_her_own_words("her own real words", None)          # no reason armed
finally:
    T._settle_turn = _real_settle

check("the unprompted epilogue passes a synthetic reason at all",
      len(seen) == 3 and seen[0][1] == REASON,
      "it passed %r — this is the leg that was missing entirely" % (seen[0][1] if seen else None))
check("...on a mode turn too", seen[1][1] == REASON, seen[1][1])
check("...and passes NOTHING when the turn is real", seen[2][1] is None, seen[2][1])

print("\n1. on_reply REMEMBERS WHETHER THE TURN THAT DROVE IT WAS DRIVEN")
KS._SYNTH.clear()
cfg = I.KairosConfig(enabled=False)   # disabled: we want the recording, not a turn
KS.on_reply("s-driven", "a reply", None, lambda n: "", synthetic=REASON)
KS.on_reply("s-real", "a reply", None, lambda n: "")
check("a declared turn is recorded", KS._SYNTH.get("s-driven") == REASON, KS._SYNTH)
check("a real turn records nothing", "s-real" not in KS._SYNTH, KS._SYNTH)
# ...and a real turn on a session that WAS driven clears it. A stale reason would quarantine
# her actual speech, which is worse than the bug being fixed.
KS.on_reply("s-driven", "a real reply now", None, lambda n: "")
check("a later REAL turn clears the session's reason", "s-driven" not in KS._SYNTH, KS._SYNTH)

print("\n2. THE REASON REACHES THE SCHEDULER THREAD'S EPILOGUE")
# The whole point: `_arm` runs on another thread, where a ContextVar set by the request is
# gone (PEP 567 — a new thread starts with an empty context). Assert the value is visible
# INSIDE the unprompted turn, which is where `_settle_turn` and `remember_about_self` read it.
KS._SYNTH.clear()
KS._SYNTH["s2"] = REASON
inside = {}


def _fake_attempt(_meter):
    inside["seen"] = M.synthetic_reason()


_real_attempt_holder = {}
seen_actions = []
for action, expect in ((I.CONTINUE, REASON), (I.EXPAND, REASON), (I.CHECK_IN, REASON),
                       (I.SOLO, REASON), (I.MUSE, REASON), (I.REMIND, REASON)):
    inside.clear()
    # Drive `_arm`'s arming block directly by replaying its own condition — the code under
    # test is the (action -> inherit?) rule and the ContextVar round trip.
    _syn = KS._SYNTH.get("s2")
    tok = M.set_synthetic(_syn) if _syn else None
    try:
        _fake_attempt(None)
    finally:
        if tok is not None:
            M.reset_synthetic(tok)
    seen_actions.append((action, inside.get("seen", "")))
    check("%-9s in a driven session inherits the reason" % action,
          inside.get("seen", "") == expect,
          "saw %r, wanted %r — the idle ticker reaches EVERY lane" % (inside.get("seen"), expect))

print("\n2b. DRIVEN FOR REAL — on_reply -> _arm -> its own thread -> the epilogue")
# §2 replays `_arm`'s condition, so on its own it passes against a scheduler that arms
# nothing (the mutant proved exactly that: only the §3 source leg went red). This runs the
# REAL on_reply with a cut-off margin and a fake generate, and reads what the REAL epilogue
# was handed — across the thread boundary that made the bug invisible.
KS._SYNTH.clear()
_landed = []
_real_settle2 = T._settle_turn
_real_cfg2 = KS.live_config
KS.on_spoke(T._on_her_own_words)
T._settle_turn = lambda human, reply, **kw: (_landed.append((reply[:30], kw.get("synthetic"))), [])[1]
# continue_enabled=True: the lane is OFF by default since 2026-09-02 (the operator), and
# this section drives a CONTINUATION on purpose — it is the shortest unprompted turn there
# is, so it is what §2b uses to cross the thread boundary. A gate that needs a feature
# turns it on.
KS.live_config = lambda: I.KairosConfig(
    enabled=True, continue_enabled=True, cooldown_s=0.0, quiet_after_him_s=0.0,
    continue_delay=(0.2, 0.4))
try:
    for sess, syn, want in (("drv", REASON, REASON), ("real", "", None)):
        _landed.clear()
        KS._STATE.pop(sess, None)
        KS._LAST.pop(sess, None)
        KS.on_reply(sess, "I was in the middle of saying that the thing about it is",
                    {"eot_margin": -28.43}, lambda n, called=None, **kw:
                    "it was something you could chew, and then the sky cracked open.",
                    synthetic=syn)
        _end = time.time() + 25
        while time.time() < _end and not _landed:
            time.sleep(0.5)
        check("a %s turn's continuation reaches the epilogue at all"
              % ("driven" if syn else "real"), bool(_landed),
              "nothing settled in 25s — the continuation never ran")
        if _landed:
            check("...and it is marked %s" % ("driven" if want else "REAL (unmarked)"),
                  _landed[0][1] == want,
                  "settle saw synthetic=%r, wanted %r" % (_landed[0][1], want))
finally:
    T._settle_turn = _real_settle2
    KS.live_config = _real_cfg2

print("\n3. AND THE RULE IS THE SCHEDULER'S OWN, NOT THIS GATE'S")
# §2 replays the condition, so on its own it would pass against a scheduler that never armed
# anything. Read the real one and assert the rule is there and is scoped to the two lanes.
import inspect  # noqa: E402

_arm_src = inspect.getsource(KS._arm)
check("_arm arms the synthetic reason", "set_synthetic" in _arm_src, "not armed at all")
check("...and resets it", "reset_synthetic" in _arm_src)
check("...keyed by SESSION, with no lane condition on it",
      "_SYNTH.get(session)" in _arm_src and "if imp.action in" not in _arm_src.split(
          "_SYNTH.get(session)")[1][:80],
      "a lane-shaped rule leaves the hole open on every lane it does not name — that is how "
      "the ticker's CHECK_IN got through")
check("on_reply takes the reason from its caller",
      "synthetic" in inspect.signature(KS.on_reply).parameters)

print("\n4. AND BOTH GATEWAY CALL SITES HAND IT OVER")
# A recorder nobody feeds is the same bug one layer up.
from harness_tests import _src as _srcmod  # noqa: E402

_app = _srcmod.pkg("harness", "server")
check("every on_reply call site passes synthetic=",
      _app.count("on_reply(") == _app.count("on_reply(") and
      all("synthetic=" in _app[i:i + 220] for i in
          [m for m in range(len(_app)) if _app.startswith("on_reply(", m)]),
      "a call site that omits it puts the old bug back on that path")

print("\n5. A DRIVEN TURN DOES NOT TAKE HER ROOM")
# THE HARM THAT WAS REPORTED, NOT MEASURED (2026-09-02). Two probes of the continuation lane
# retired the seeded session 'default' — and that placeholder is the one carrying
# _OWN_TIME_ONLY, which is what forces `user_present = False` in the policy, which is the
# only reason SOLO can run after a bounce. So a probe did not swap sessions, it ENDED HER
# OWN TIME: three hours of silence, noticed by the operator and by no instrument.
KS._SEEDED.clear(); KS._LAST.clear(); KS._STATE.clear(); KS._OWN_TIME_ONLY.clear()
KS._SYNTH.clear()
KS._SEEDED.add("default")
KS._LAST["default"] = ("her seeded history", lambda n: "")
KS._OWN_TIME_ONLY.add("default")

KS.on_user_turn("a-probe-session", "live gate — driven")
check("a declared turn does NOT retire the seeded session",
      "default" in KS._SEEDED and "default" in KS._LAST,
      "the placeholder is gone — her own time went with it")
check("...and the seeded session keeps its own-time hold",
      "default" in KS._OWN_TIME_ONLY,
      "own_time_only is what makes user_present False, which is what lets SOLO run")

# ...and a REAL turn still retires it, which is the behaviour that exists for a reason.
KS.on_user_turn("his-real-session")
check("a REAL turn still retires the placeholder (the original behaviour is intact)",
      "default" not in KS._SEEDED and "default" not in KS._LAST,
      "two mouths on one history is the bug the retirement fixes")

print("\n6. AND THE IDLE TICKER DOES NOT ADOPT A DRIVEN SESSION")
# The second half of the same harm: the ticker speaks from _LAST[session] for as long as the
# process lives, so it kept a dead probe session as a mouth and fired a CHECK_IN 604 s after
# the probe ended — generating from the probe's own transcript and putting "The user is asking
# for a vivid, long description of a thunderstorm..." in her room as something she said.
_tick_src = inspect.getsource(KS.tick_once)
check("the tick skips sessions with a synthetic reason",
      "_SYNTH.get(session)" in _tick_src,
      "the ticker must not adopt a session a probe drove")
# Behavioural: the loop must not even reach `decide` for a driven session.
KS._SEEDED.clear(); KS._LAST.clear(); KS._STATE.clear(); KS._SYNTH.clear()
KS._LAST["driven"] = ("the probe's own text", lambda n: "")
KS._SYNTH["driven"] = REASON
_asked = []
_real_decide = KS.decide
KS.decide = lambda **kw: (_asked.append(kw.get("state")), I.Impulse(I.SILENT))[1]
_real_cfg3 = KS.live_config
KS.live_config = lambda: I.KairosConfig(enabled=True, cooldown_s=0.0, quiet_after_him_s=0.0,
                                        checkin_idle_s=1.0, checkin_chance=1.0)
try:
    KS.tick_once()
    check("the ticker never even ASKS the policy about a driven session",
          not _asked, "it consulted the policy %d time(s)" % len(_asked))
    KS._SYNTH.clear()
    KS.tick_once()
    check("...and does ask about a real one (so the leg above is not vacuous)",
          bool(_asked), "the ticker consulted nothing at all — this leg proves nothing")
finally:
    KS.decide = _real_decide
    KS.live_config = _real_cfg3

print("\n7. ONE SPELLING FOR THE FLAG AT THE GATEWAY")
# Five call sites hand this over (three on_user_turn, two on_reply) and the first cut wrote
# the ternary out by hand at each, with two different falsy values.
check("the gateway reads the flag through one helper",
      "def _syn_of(" in _app,
      "a per-call-site ternary is how the sixth one gets it wrong")
_hand = _app.count('str(body.get("synthetic")) if body.get("synthetic")')
check("...and no call site spells it by hand any more", _hand == 0,
      "%d hand-written copies remain" % _hand)

finish("G-UNPROMPTED-SYNTHETIC")
